#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'pio_led', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_LED_'.
 * The prefix is the slave descriptor.
 */
#define PIO_LED_COMPONENT_TYPE altera_avalon_pio
#define PIO_LED_COMPONENT_NAME pio_led
#define PIO_LED_BASE 0x0
#define PIO_LED_SPAN 32
#define PIO_LED_END 0x1f
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 10
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE NONE
#define PIO_LED_FREQ 50000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ_TYPE NONE
#define PIO_LED_RESET_VALUE 1023

/*
 * Macros for device 'pio_sw', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_SW_'.
 * The prefix is the slave descriptor.
 */
#define PIO_SW_COMPONENT_TYPE altera_avalon_pio
#define PIO_SW_COMPONENT_NAME pio_sw
#define PIO_SW_BASE 0x10
#define PIO_SW_SPAN 32
#define PIO_SW_END 0x2f
#define PIO_SW_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_SW_CAPTURE 0
#define PIO_SW_DATA_WIDTH 10
#define PIO_SW_DO_TEST_BENCH_WIRING 0
#define PIO_SW_DRIVEN_SIM_VALUE 0
#define PIO_SW_EDGE_TYPE NONE
#define PIO_SW_FREQ 50000000
#define PIO_SW_HAS_IN 1
#define PIO_SW_HAS_OUT 0
#define PIO_SW_HAS_TRI 0
#define PIO_SW_IRQ_TYPE NONE
#define PIO_SW_RESET_VALUE 0

/*
 * Macros for device 'hex_mux', class 'hex_mux'
 * The macros are prefixed with 'HEX_MUX_'.
 * The prefix is the slave descriptor.
 */
#define HEX_MUX_COMPONENT_TYPE hex_mux
#define HEX_MUX_COMPONENT_NAME hex_mux
#define HEX_MUX_BASE 0x20
#define HEX_MUX_SPAN 4
#define HEX_MUX_END 0x23

/*
 * Macros for device 'sweep_logic_ctrl', class 'sweep_logic'
 * The macros are prefixed with 'SWEEP_LOGIC_CTRL_'.
 * The prefix is the slave descriptor.
 */
#define SWEEP_LOGIC_CTRL_COMPONENT_TYPE sweep_logic
#define SWEEP_LOGIC_CTRL_COMPONENT_NAME sweep_logic
#define SWEEP_LOGIC_CTRL_BASE 0x30
#define SWEEP_LOGIC_CTRL_SPAN 4
#define SWEEP_LOGIC_CTRL_END 0x33

/*
 * Macros for device 'sweep_logic_stat', class 'sweep_logic'
 * The macros are prefixed with 'SWEEP_LOGIC_STAT_'.
 * The prefix is the slave descriptor.
 */
#define SWEEP_LOGIC_STAT_COMPONENT_TYPE sweep_logic
#define SWEEP_LOGIC_STAT_COMPONENT_NAME sweep_logic
#define SWEEP_LOGIC_STAT_BASE 0x34
#define SWEEP_LOGIC_STAT_SPAN 4
#define SWEEP_LOGIC_STAT_END 0x37

/*
 * Macros for device 'sweep_logic_cntsclk', class 'sweep_logic'
 * The macros are prefixed with 'SWEEP_LOGIC_CNTSCLK_'.
 * The prefix is the slave descriptor.
 */
#define SWEEP_LOGIC_CNTSCLK_COMPONENT_TYPE sweep_logic
#define SWEEP_LOGIC_CNTSCLK_COMPONENT_NAME sweep_logic
#define SWEEP_LOGIC_CNTSCLK_BASE 0x38
#define SWEEP_LOGIC_CNTSCLK_SPAN 4
#define SWEEP_LOGIC_CNTSCLK_END 0x3b

/*
 * Macros for device 'sweep_logic_low', class 'sweep_logic'
 * The macros are prefixed with 'SWEEP_LOGIC_LOW_'.
 * The prefix is the slave descriptor.
 */
#define SWEEP_LOGIC_LOW_COMPONENT_TYPE sweep_logic
#define SWEEP_LOGIC_LOW_COMPONENT_NAME sweep_logic
#define SWEEP_LOGIC_LOW_BASE 0x3c
#define SWEEP_LOGIC_LOW_SPAN 4
#define SWEEP_LOGIC_LOW_END 0x3f

/*
 * Macros for device 'sweep_logic_high', class 'sweep_logic'
 * The macros are prefixed with 'SWEEP_LOGIC_HIGH_'.
 * The prefix is the slave descriptor.
 */
#define SWEEP_LOGIC_HIGH_COMPONENT_TYPE sweep_logic
#define SWEEP_LOGIC_HIGH_COMPONENT_NAME sweep_logic
#define SWEEP_LOGIC_HIGH_BASE 0x40
#define SWEEP_LOGIC_HIGH_SPAN 4
#define SWEEP_LOGIC_HIGH_END 0x43

/*
 * Macros for device 'FPGA_CHIP_LOGIC_cpuctrl', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_CPUCTRL_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_CPUCTRL_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_CPUCTRL_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_CPUCTRL_BASE 0x44
#define FPGA_CHIP_LOGIC_CPUCTRL_SPAN 4
#define FPGA_CHIP_LOGIC_CPUCTRL_END 0x47

/*
 * Macros for device 'FPGA_CHIP_LOGIC_cpustat', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_CPUSTAT_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_CPUSTAT_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_CPUSTAT_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_CPUSTAT_BASE 0x48
#define FPGA_CHIP_LOGIC_CPUSTAT_SPAN 4
#define FPGA_CHIP_LOGIC_CPUSTAT_END 0x4b

/*
 * Macros for device 'FPGA_CHIP_LOGIC_cntsclk', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_CNTSCLK_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_CNTSCLK_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_CNTSCLK_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_CNTSCLK_BASE 0x4c
#define FPGA_CHIP_LOGIC_CNTSCLK_SPAN 4
#define FPGA_CHIP_LOGIC_CNTSCLK_END 0x4f

/*
 * Macros for device 'FPGA_CHIP_LOGIC_adc', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_ADC_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_ADC_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_ADC_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_ADC_BASE 0x50
#define FPGA_CHIP_LOGIC_ADC_SPAN 4
#define FPGA_CHIP_LOGIC_ADC_END 0x53

/*
 * Macros for device 'FPGA_CHIP_LOGIC_scan_chain', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_SCAN_CHAIN_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_SCAN_CHAIN_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_SCAN_CHAIN_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_SCAN_CHAIN_BASE 0x54
#define FPGA_CHIP_LOGIC_SCAN_CHAIN_SPAN 4
#define FPGA_CHIP_LOGIC_SCAN_CHAIN_END 0x57

/*
 * Macros for device 'FPGA_CHIP_LOGIC_sram_addr_wrt', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_BASE 0x58
#define FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_SPAN 4
#define FPGA_CHIP_LOGIC_SRAM_ADDR_WRT_END 0x5b

/*
 * Macros for device 'FPGA_CHIP_LOGIC_sram_data_wrt', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_SRAM_DATA_WRT_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_SRAM_DATA_WRT_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_DATA_WRT_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_DATA_WRT_BASE 0x5c
#define FPGA_CHIP_LOGIC_SRAM_DATA_WRT_SPAN 4
#define FPGA_CHIP_LOGIC_SRAM_DATA_WRT_END 0x5f

/*
 * Macros for device 'FPGA_CHIP_LOGIC_sram_addr_rd', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_SRAM_ADDR_RD_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_SRAM_ADDR_RD_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_ADDR_RD_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_ADDR_RD_BASE 0x60
#define FPGA_CHIP_LOGIC_SRAM_ADDR_RD_SPAN 4
#define FPGA_CHIP_LOGIC_SRAM_ADDR_RD_END 0x63

/*
 * Macros for device 'FPGA_CHIP_LOGIC_sram_data_rd', class 'SRAM_IO_CTRL_LOGIC'
 * The macros are prefixed with 'FPGA_CHIP_LOGIC_SRAM_DATA_RD_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_CHIP_LOGIC_SRAM_DATA_RD_COMPONENT_TYPE SRAM_IO_CTRL_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_DATA_RD_COMPONENT_NAME FPGA_CHIP_LOGIC
#define FPGA_CHIP_LOGIC_SRAM_DATA_RD_BASE 0x64
#define FPGA_CHIP_LOGIC_SRAM_DATA_RD_SPAN 4
#define FPGA_CHIP_LOGIC_SRAM_DATA_RD_END 0x67

/*
 * Macros for device 'spi_int_0', class 'altera_avalon_spi'
 * The macros are prefixed with 'SPI_INT_0_'.
 * The prefix is the slave descriptor.
 */
#define SPI_INT_0_COMPONENT_TYPE altera_avalon_spi
#define SPI_INT_0_COMPONENT_NAME spi_int_0
#define SPI_INT_0_BASE 0x100
#define SPI_INT_0_SPAN 64
#define SPI_INT_0_END 0x13f
#define SPI_INT_0_IRQ 3
#define SPI_INT_0_CLOCKMULT 1
#define SPI_INT_0_CLOCKPHASE 0
#define SPI_INT_0_CLOCKPOLARITY 0
#define SPI_INT_0_CLOCKUNITS "Hz"
#define SPI_INT_0_DATABITS 16
#define SPI_INT_0_DATAWIDTH 16
#define SPI_INT_0_DELAYMULT "1.0E-9"
#define SPI_INT_0_DELAYUNITS "ns"
#define SPI_INT_0_EXTRADELAY 0
#define SPI_INT_0_INSERT_SYNC 0
#define SPI_INT_0_ISMASTER 1
#define SPI_INT_0_LSBFIRST 0
#define SPI_INT_0_NUMSLAVES 4
#define SPI_INT_0_PREFIX "spi_"
#define SPI_INT_0_SYNC_REG_DEPTH 2
#define SPI_INT_0_TARGETCLOCK 500000
#define SPI_INT_0_TARGETSSDELAY "0.0"

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1494131643

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 16
#define JTAG_UART_END 0x2000f
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
